#.travis.yml

language: node_js
node_js:
  - "8.11.3"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href /

notifications:
  email:
    on_failure: change
    on_success: change
